feat: setup runtime types, setup game skeleton
inmyshoesdev/inmyshoes pull request #7
Opened 2021-10-01 20:48 UTC by weiijiie

- Added runtime types
- Setup basic game skeleton based on [prototype](https://svelte.dev/repl/5ec93c82e4ab439b9e3d98862cc4de5a?version=3.43.0)
- Used [zustand](https://github.com/pmndrs/zustand) for state management -> very simple API based around mutating a global store
- Used [immer](https://github.com/immerjs/immer) to help make mutations simpler

Visit `/testing` and press `Load Example` to load the example JSON and display the game.

2021-10-01 23:28 UTC, tlylt requested changes
Great job for setting up the overall game flow 👍 , I added some minor comments to address or clarify, and afterward it should be good to merge. We should be able to work off this implementation and make the individual components work well.

2021-10-01 23:28 UTC, tlylt commented on schema/actions.ts
> +])
The comment for this seems outdated, as now the type could also be a string?

2021-10-01 23:28 UTC, tlylt commented on pages/testing.tsx
> +      {game && <GameDisplay game={game}></GameDisplay>}
perhaps can use self closing `<GameDisplay game={game} />`

2021-10-01 23:28 UTC, tlylt commented on stores/store.ts
> +            let newGame = produce<Game>(state.game, (game) => {
can this be const?

2021-10-01 23:28 UTC, tlylt commented on lib/scene.ts
> +  let id = schema.id
can this be `const` ? or just replace the usage of `id` with `schema.id` below?

2021-10-01 23:28 UTC, tlylt commented on lib/actions.ts
> +    let narration = getNarration(game, sceneId, value)
can possibly be `const` ?

2021-10-02 09:09 UTC, weiijiie commented on lib/actions.ts
> +    let narration = getNarration(game, sceneId, value)
yup, will change!

2021-10-02 09:09 UTC, weiijiie commented on lib/scene.ts
> +  let id = schema.id
yea, changing to const

2021-10-02 09:10 UTC, weiijiie commented on stores/store.ts
> +            let newGame = produce<Game>(state.game, (game) => {
sure, changing to const too

2021-10-02 09:10 UTC, weiijiie commented on pages/testing.tsx
> +      {game && <GameDisplay game={game}></GameDisplay>}
sure, updated!

2021-10-02 09:14 UTC, weiijiie commented on schema/actions.ts
> +])
the comment still seems to be accurate to me? basically an action schema must have `type` and `duration` (or leave duration blank), and the rest of the fields can be captured as a record of string to any.

2021-10-02 09:21 UTC, tlylt commented on lib/actions.ts
> +export type ModifyableArgs = {
a minor nit, should be `ModifiableArgs` ?

2021-10-02 09:36 UTC, weiijiie commented on lib/actions.ts
> +export type ModifyableArgs = {
HAHA yeah

2021-10-02 10:19 UTC, tlylt approved these changes

2021-10-02 10:20 UTC, merged