Fix reselect character bug
inmyshoesdev/inmyshoes pull request #83
Opened 2021-11-09 18:09 UTC by shiweing

2021-11-09 23:18 UTC, tlylt requested changes

2021-11-09 23:18 UTC, tlylt commented on schema/mvp.json
> -    "hyperfocus wildcard appeared": false
er is there a reason why this is removed? hyperfocus wildcard is for belinda I think.

2021-11-09 23:18 UTC, tlylt commented on schema/mvp.json
> -                  }
For all these, have you updated the image or? I think it was there to fix the dimension issues

2021-11-10 01:40 UTC, shiweing commented
@tlylt I might have done something by mistake, I've added them back. Thanks for pointing that out

2021-11-10 01:44 UTC, tlylt approved these changes
LGTM

2021-11-10 01:50 UTC, merged